### ISSUE TITLE
Wrong key just renewed it 

### ISSUE THREAD

**Issue by Sgfguy417** [northloopforensics/Bitlocker_Key_Finder#2]

**Comment by Sgfguy417** [comment]
Windows 11 pro upgrade now I can't even log in

**Comment by northloopforensics** [comment]
Hi, can you provide additional information?
What key? What renewal? Can’t log into what?

**Comment by Sgfguy417** [comment]
Windows 11 pro . Bitlocker rebooted and it was the wrong key. I can't even open my PC now. Amd ryzen 7

**Comment by northloopforensics** [comment]
I'm sorry to hear that. Unfortunately, this tool is not going to be able to help you access the system.  It can only access Bitlocker information on unlocked/unencrypted systems.  I'd recommend reaching out to Microsoft and seeking some way to roll back the upgrade so you can get your data back.  

Best of luck. I hope you get it resolved.
