### ISSUE TITLE
BEK file

### ISSUE THREAD

**Issue by MaxFuwin** [northloopforensics/Bitlocker_Key_Finder#4]
Hi,
My System is Windows10 home edition, my computer was locked by BitLocker and I could only find the recovery key for my system drive. But I cannot find the recovery key for other drive(D Drve), i viewed the key protectors in manage bde and I saw there were two protectors supported for my D drive, one is recovery key the other one is bek. I also had searched bek files on "Everything" but I didn't find it, so can BitLocker_key_finder help me to recover the .bek files for my D drive?
MaxFuwin

**Comment by northloopforensics** [comment]
Yes, if the BEK file is stored to a piece of media you have access to. The tool is really not much more than a file-search looking for, in your case, a file with extension “.BEK”.  It just speeds up the process a bit and narrows the search focus for recovery keys.

Normally, BEK files are placed on thumb drives to act as a hardware key for Bitlocked devices. Perhaps you put it on a thumb drive, or perhaps even your C: drive?

This may be helpful: https://superuser.com/questions/1674672/where-is-my-bitlocker-bek-file

I wish you the very best of luck getting access to your data.
